# -*- coding: utf-8 -*-
"""Recbole.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WSf_l0RkplIeQ47Cp4aSCiPqJ_vhTqis
"""

!apt install libomp-dev
!pip install faiss

import numpy as np
import faiss
import requests
from io import StringIO
import pandas as pd

random_array = np.array(np.random.rand(8,6), dtype = 'float32')
random_array.shape
d = random_array.shape[1]

random_array

d

index2 = faiss.IndexFlatL2(d)
index2.is_trained
index2.add(random_array)
index2.ntotal

xq = np.transpose(np.array([1,2,3,4,5,6],dtype = 'float32').reshape(-1,1))

xq.shape

index2.search(xq, k =2)  # search

